### ISSUE TITLE
can display parental code ?

### ISSUE THREAD

**Issue by yakaracolombia** [GaryOderNichts/recovery_menu#1]
I try to recover a Wiiu with lock user and lock boot screen with parental code lock, can be added an option to disable or show the parental code in the recovery menu?

**Comment by GaryOderNichts** [comment]
Sorry for the late reply.
In most cases you can just use the [mkey site](https://mkey.salthax.org/).

If that doesn't work, you can use wupclient to connect to wupserver, which allows downloading the parental configuration.
Download python and the [wupclient script](https://gist.githubusercontent.com/GaryOderNichts/409672b1bd5627b9dc506fe0f812ec9e/raw/7d6b99d2d53cc3273fb041a53ec9020dc7d7d511/wupclient.py).
Then start wupserver from the recovery_menu and edit the IP address in the script (line 30) with the one that gets displayed.
Now run `python -i wupclient.py` using a terminal/cmd in the same folder and the script should connect to wupserver.
You can now enter `w.dl("/vol/system/proc/prefs/parent.xml")` to download the parental configuration containing the pin code.

**Comment by GaryOderNichts** [comment]
Implemented in version 0.2
