### ISSUE TITLE
TV out support for the recovery menu?

### ISSUE THREAD

**Issue by AnticsTheHanyou** [GaryOderNichts/recovery_menu#3]
Hello, and first off, thank you for this development.  I've had a WiiU that was stupidly factory reset with CBHC and hope to finally be able to recover it.

I'm attempting to load the recovery menu and it appears to be booting, however I don't see it on the TV screen. Based on the videos I've seen of its use, it appears it only supports video out through the gamepad which is no longer paired to the WiiU.

Is it possible to add TV/HDMI support for the recovery menu?

**Comment by GaryOderNichts** [comment]
It seems like TV output doesn't currently work properly if it wasn't properly setup previously.
Can you test if TV output works with the following build? The menu might look a bit blue now and gamepad output doesn't work, as this is still WIP, but maybe it will show TV output.
[recovery_menu.zip](https://github.com/GaryOderNichts/recovery_menu/files/8884945/recovery_menu.zip)

If not you'll have to navigate the menu blindly, based on the screenshots I attached below :P

![Screenshot 2022-06-06 17-32-06](https://user-images.githubusercontent.com/12049776/173209215-82c8ad6b-ebec-429c-aba9-626ce8967376.png)
![Screenshot 2022-06-06 17-32-25](https://user-images.githubusercontent.com/12049776/173209216-faeafdbe-5df4-47f0-b612-39b2c1b3b5e9.png)

**Comment by AnticsTheHanyou** [comment]
Amazing! That one loaded up perfectly, I was able to reset the CHBC title, and this Wind Waker WiiU has new life!

Thank you, thank you, thank you!!!!

**Comment by GaryOderNichts** [comment]
Awesome! I'm going to keep this issue open until TV support is properly implemented.

**Comment by arcangelweb** [comment]
It worked perfectly with a wii or error 160-0101, without a pad. 

![PXL_20220614_145730605](https://user-images.githubusercontent.com/8561820/173626430-231a9ff6-a84b-4879-ad95-2967abf29587.jpg)

![PXL_20220614_152738191](https://user-images.githubusercontent.com/8561820/173626533-831c6cb5-b170-45b5-866e-2d19877d8282.jpg)

 Console recovered.  Thank you

**Comment by einso** [comment]
FYI: The video out does not work if the console is set to AV out, which is the factory default. So if you removed the CRC battery at some point, it will default to AV. The recovery_menu build then forces the output to HDMI, which shows either garbled or blank. But the menu is there and navigating it blind, thanks to the screenshots, helped fix my bricked console.

**Comment by GaryOderNichts** [comment]
Version 0.2 now comes with a display controller initialization build.

**Comment by markdude701** [comment]
> It seems like TV output doesn't currently work properly if it wasn't properly setup previously. Can you test if TV output works with the following build? The menu might look a bit blue now and gamepad output doesn't work, as this is still WIP, but maybe it will show TV output. [recovery_menu.zip](https://github.com/GaryOderNichts/recovery_menu/files/8884945/recovery_menu.zip)
> 
> **For everyone else stumbling across this issue:** Here is an updated build which has proper colors: [recovery_menu.zip](https://github.com/GaryOderNichts/recovery_menu/files/8904060/recovery_menu.zip) Note that all of these builds don't support GamePad output and only output 480p, which is why they're not official releases yet.
> 
> If not you'll have to navigate the menu blindly, based on the screenshots I attached below :P
> 
> ![Screenshot 2022-06-06 17-32-06](https://user-images.githubusercontent.com/12049776/173209215-82c8ad6b-ebec-429c-aba9-626ce8967376.png) ![Screenshot 2022-06-06 17-32-25](https://user-images.githubusercontent.com/12049776/173209216-faeafdbe-5df4-47f0-b612-39b2c1b3b5e9.png)

Had this issue today. I know this issue is closed but found this thread and wanted to thank you for fixing my Wii U with this comment. You made me so happy, I'm positively elated knowing I don't have to buy another one. Thanks again friend! Cheers!
