### ISSUE TITLE
MCP_setsysprobsettings() failed: fffbffee when trying to fix region

### ISSUE THREAD

**Issue by tuner357** [GaryOderNichts/recovery_menu#37]
Hey! 

I just rebuilt the mlc on a Japanese wii u with a 64gb nand aid, now im trying to fix the region as i want it to be usa.  System region code and game region code are both jpn. But when i try to switch to usa using "debug system region" option i get this error "MCP_setsysprobsettings() failed: fffbffee"

What am i doing wrong?

**Comment by GaryOderNichts** [comment]
Sounds like your `sys_prod.xml` has the wrong `access` value set for some of the entries.
Also note that the "Debug System Region" option only makes sure your system version doesn't mismatch.
It doesn't allow for setting a different region.

**Comment by tuner357** [comment]
you are 100% right. changed sys_prod.xml and now everything shows usa. just have to find out why its still not booting properly and giving me a 160-0103 still! thanks for the reply
