### ISSUE TITLE
The recovery_menu cannot be loaded by using Pico

### ISSUE THREAD

**Issue by jimmy-che** [GaryOderNichts/recovery_menu#4]
Hey, man. Thanks for your great job!

I follow your instructions and youtube video to unbrick my WiiU by using Pico, but nothing happen. The recovery_menu cannot be loaded.

Did I miss something by using Pico?

**Comment by GaryOderNichts** [comment]
There is a build available with better TV output support [here](https://github.com/GaryOderNichts/recovery_menu/issues/3#issuecomment-1153030434).

The log you attached included logs from running udpih, can you upload an earlier log which was generated by starting the console up normally?
One thing which doesn't look normal is this line though:
```
00;00;09;875: *** KeGetSharedArea() - area not loaded.
00;00;09;875: Error: Root could not get shared font data for font 0
```
Is the `CafeStd.ttf` font in `/vol/storage_mlc01/sys/title/0005001b/10042400/content`? You could check using wupserver/wupclient, by running `w.ls("/vol/storage_mlc01/sys/title/0005001b/10042400/content")`.

**Comment by jimmy-che** [comment]
@GaryOderNichts 

Thank you very much!
Now I give up to save my WiiU.

**Comment by mitch030504** [comment]
im having the exact same issue, any way to fix it as of now?

**Comment by jan-hofmeier** [comment]
For anyone stumbling on this: yes it is fixable now (or since well over a year).
You would install ISFShax through UDPIH (works without seeing the menu); https://gbatemp.net/threads/how-to-set-up-isfshax.642258/ and then either use redNAND or use MLC2SD and rebuild the MLC.
