### ISSUE TITLE
No signal and black screen on the TV

### ISSUE THREAD

**Issue by HyanaMongus** [GaryOderNichts/recovery_menu#6]
Hello, I'm currently trying to fix my CBHC Bricked Wii U, I bought everything I was missing (a raspberry pico and a USB SD card reader) but when I plug the pico into the Wii U I just have no signal so I tried the "dc_init" one and same problem. Tried another TV and same problem.

Before doing this issue I looked if someone had the same problem and it was almost the same ( #3 ). I tried the version that was uploaded and I got a black screen, nothing at all, so I thought that was fine and I just had to press the buttons blindly but nothing, like the menu hadn't started.

I double checked if everything was good and it was. My sd card was formatted in FAT32 (with 32k allocation unit size). The file was in the root of the sd card, the pico was correctly flashed.

(also, my gamepad is not synchronized with the console in case if thats the problem...)

I don't know where I screwed up so I'm asking for help here...

Thanks

**Comment by GaryOderNichts** [comment]
Does your console power off if you run udpih without an SD Card inserted?

**Comment by HyanaMongus** [comment]
Just tried and nop, I checked if the Wii U is still working and yes.

**Comment by GaryOderNichts** [comment]
Then udpih isn't properly started and the recovery_menu isn't loaded yet.
Make sure to keep all of this in mind:
> :warning: Important notes for this to work:
> - Make sure **no** other USB Devices are attached to the console.
> - Only use USB ports on the front of the console, the back ports **will not** work.
> - If your console has standby mode enabled, pull the power plug and turn it on from a full coldboot state.

**Comment by HyanaMongus** [comment]
and yes that what I saw, since my tv doesn't show the Wii U logo (it takes time for some reason) maybe the timing is the problem?
or do I need to reflash the pico?

**Comment by HyanaMongus** [comment]
Ok it was my timing the console powered off without the SD, my bad.

**Comment by HyanaMongus** [comment]
It finally worked! I did it blindly and now i'm on the menu. 

Thanks a lot !
